In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [ ]:
df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
def initialize_parameters(layer_dims):

  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))


  return parameters

In [ ]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def linear_forward(A_prev, W, b):

  Z = np.dot(W.T, A_prev) + b

  return Z

In [ ]:
# Forward Prop
def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network

  for l in range(1, L+1):
    A_prev = A
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)

  return A,A_prev

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [ ]:
y_hat = y_hat[0][0]

In [ ]:
A1

array([[1.6],
       [1.6]])

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

In [ ]:
parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

In [ ]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_12066/332058445.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
/tmp/ipykernel_12066/332058445.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
/tmp/ipykernel_12066/332058445.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))
/tmp/ipykernel_12066/332058445.py:6: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
/tmp/ipykernel_12066/332058445.py:7: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
/tmp/ipykernel_12066/332058445.py:8: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])
/tmp/ipykernel_12066/332058445.py:10: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
/tmp/ipykernel_12066/332058445.py:11: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
/tmp/ipykernel_12066/332058445.py:12: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:
parameters

{'W1': array([[0.11533984, 0.1276017 ],
        [0.11533984, 0.1276017 ]]),
 'b1': array([[0.00257437],
        [0.00257437]]),
 'W2': array([[0.13525283],
        [0.13525283]]),
 'b2': array([[0.14820409]])}

In [ ]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [ ]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.11458955, 0.1168776 ],
        [0.11458955, 0.1168776 ]]),
 'b1': array([[0.0019667],
        [0.0019667]]),
 'W2': array([[0.12712927],
        [0.12712927]]),
 'b2': array([[0.13612818]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.12409711, 0.13272353],
        [0.12412266, 0.13276611]]),
 'b1': array([[0.00355129],
        [0.00355555]]),
 'W2': array([[0.14692424],
        [0.14731907]]),
 'b2': array([[0.15810417]])}

In [ ]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training exaplme)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.13482804, 0.15847776],
        [0.1349909 , 0.15884991]]),
 'b1': array([[0.00569748],
        [0.0057292 ]]),
 'W2': array([[0.17312488],
        [0.17534027]]),
 'b2': array([[0.18773702]])}

In [ ]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962

{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

USING KERAS

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame(
    [[8,8,4],
     [7,9,5],
     [6,10,6],
     [5,12,7]],
    columns=['cgpa','profile_score','lpa']
)

df

   cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()

model.add(Dense(2,
                activation='linear',
                input_dim=2))

model.add(Dense(1,
                activation='linear'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[-0.32761186, -0.35892296],
        [-0.727842  , -0.9738206 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.4061924],
        [0.3166337]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights = [

np.array([[0.1,0.1],
          [0.1,0.1]],dtype=np.float32),

np.array([0.,0.],dtype=np.float32),

np.array([[0.1],
          [0.1]],dtype=np.float32),

np.array([0.],dtype=np.float32)

]

In [ ]:
model.set_weights(new_weights)  # apply weights

In [ ]:
optimizer = keras.optimizers.Adam(
    learning_rate=0.001
)

model.compile(
    loss='mean_squared_error',
    optimizer=optimizer
)

In [ ]:
model.fit(
    df.iloc[:,:-1].values,
    df['lpa'].values,
    epochs=75,
    verbose=1,
    batch_size=1
)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 27.8784
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 27.5826
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 27.2289
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.8883
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.5526
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 26.2030
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.8133
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 25.4447
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 25.0233
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.6338
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 24.2445
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.8147
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 23.3716
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.8977
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 22.4934
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 21.9851
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 21.5084
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 21.0384
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.5461
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 20.0873
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.5701
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 19.0161
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.5649
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 18.0168
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 17.4887
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 16.9668
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 16.4570
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 15.9086
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 15.4222
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 14.8742
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 14.3670
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.8422
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 13.3237
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 12.7651
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 12.3171
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.7952
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 11.2741
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 10.7982
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 10.3421
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 9.8815
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 9.4321
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.9617
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 8.4971
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 8.1518
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.6761
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7.2856
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.9561
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6.5085
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 6.2192
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.8575
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.4945
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 5.1951
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.9312
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.6316
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 4.3136
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 4.0835
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.8447
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.6551
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.3954
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.2129
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 3.0448
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.8424
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.7148
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 2.5300
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.3840
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.2897
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 2.1154
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 2.0169
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.9225
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.8487
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7885
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.7041
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.5942
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.5607
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.4828

In [ ]:
model.get_weights()

[array([[0.37342316, 0.37342316],
        [0.3655527 , 0.3655527 ]], dtype=float32),
 array([0.27219242, 0.27219242], dtype=float32),
 array([[0.3728016],
        [0.3728016]], dtype=float32),
 array([0.20481686], dtype=float32)]